# Generated by Django 6.0 on 2026-01-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_alter_appointment_doctor_alter_appointment_patient_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvé"),
                    ("rejected", "Refusé"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
